# Notebook 1 – Introduction to Deep Learning

**Sprint 9 – Deep Learning Fundamentals & Neural Networks**

**Method for every concept:** Concept → Explain in my own words → Real-world analogy → Implement (small code) → Interpret the result.

## Setup

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
torch.manual_seed(42)
np.random.seed(42)
print("PyTorch version:", torch.__version__)

PyTorch version: 2.14.0+cpu



## 1. What is Deep Learning?

**Explain:** Deep Learning is ML using neural networks with **many stacked layers**, which let the model learn patterns directly from raw data instead of hand-designed features.

**Analogy:** Recognizing a face isn't one rule — your brain builds it up in stages (edges → shapes → face). A deep network does the same, layer by layer.

**Implement:**

In [3]:
shallow = nn.Sequential(nn.Linear(4, 1))                                
deep = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))       
print(shallow)
print(deep)

Sequential(
  (0): Linear(in_features=4, out_features=1, bias=True)
)
Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)


**Interpret:** The shallow model is one straight-line equation. The deep model adds a hidden layer with a non-linear activation, letting it learn more complex patterns.


## 2. AI vs ML vs Deep Learning

**Explain:** They are **nested**: AI = broad goal of intelligent behavior. ML = a subset of AI that **learns from data**. Deep Learning = a subset of ML using **multi-layer neural networks**.

**Analogy:** AI is "transportation", ML is "vehicles", Deep Learning is "cars" — each one narrower than the last.

**Implement:**

In [4]:
rule_based = lambda x: x > 50          
from sklearn.linear_model import LogisticRegression
ml = LogisticRegression().fit([[10],[90]], [0,1])  
print("Rule (AI):", rule_based(60))
print("Learned (ML):", ml.predict([[60]])[0])

Rule (AI): True
Learned (ML): 1


**Interpret:** The rule was written by hand (no data). Logistic Regression learned its answer from 2 examples. Deep Learning would use the same idea but with a neural network instead of a simple model.


## 3. Traditional ML vs Deep Learning

**Explain:** Traditional ML usually needs **hand-crafted features** and works well on small/structured data. Deep Learning can learn features **automatically**, and needs more data to do it well.

**Analogy:** Traditional ML is a chef using pre-chopped ingredients (engineered features). Deep Learning is a chef who takes raw ingredients and figures out the prep work itself.

**Implement:**

In [6]:
import pandas as pd
df = pd.read_csv('data.csv', encoding='latin1').dropna(subset=['CustomerID'])
df = df[(df.Quantity > 0) & (df.UnitPrice > 0)].sample(500, random_state=0)
X = df[['Quantity', 'UnitPrice']].values.astype('float32')
y = (df.Country != 'United Kingdom').astype('float32').values
print("Data shape:", X.shape, "| International share:", y.mean().round(2))

Data shape: (500, 2) | International share: 0.09


**Interpret:** This is the same kind of small, structured (tabular) data traditional ML is built for. A deep network *could* be used here too, but it needs more data/tuning to actually beat a simple model — DL's real edge is on images/text/audio, not small tables like this.


## 4. Why Neural Networks Are Required

**Explain:** Many real patterns are **non-linear**. Neural networks can learn curved decision boundaries that a single straight line cannot.

**Analogy:** No single straight rule can separate a circle from the ring around it — you need a flexible, non-linear boundary.

**Implement:**

In [7]:
from sklearn.datasets import make_circles
Xc, yc = make_circles(n_samples=200, noise=0.05, factor=0.4, random_state=0)
linear_acc = LogisticRegression().fit(Xc, yc).score(Xc, yc)
print("Straight-line model accuracy on a ring shape:", round(linear_acc, 2))

Straight-line model accuracy on a ring shape: 0.5


**Interpret:** A straight-line model barely beats a coin flip on this ring-shaped data — no straight line can separate a circle from its ring. This is exactly why we need networks with non-linear activations.


## 5. Applications of Deep Learning

**Explain:** Common uses: image recognition, speech recognition, language/chatbots, recommendations, fraud detection, medical imaging, self-driving cars.

**Analogy:** One core recipe (a trained deep network) can be adapted to many different "dishes" (tasks) just by changing the ingredients (data).

**Implement:**

In [8]:
applications = ["Image recognition", "Speech recognition", "Chatbots/translation",
                "Recommendations", "Fraud detection", "Medical imaging", "Self-driving cars"]
for a in applications:
    print("-", a)

- Image recognition
- Speech recognition
- Chatbots/translation
- Recommendations
- Fraud detection
- Medical imaging
- Self-driving cars


**Interpret:** All of these tasks involve complex, raw, unstructured data (pixels, sound waves, text) — exactly where Deep Learning's ability to learn its own features pays off most.


## 6. Supervised Deep Learning

**Explain:** The network trains on **labeled data** — every input has a known correct answer. It adjusts itself to match those answers.

**Analogy:** Like studying with an answer key — you check each answer and correct your understanding.

**Implement:**

In [9]:
labels_known = pd.DataFrame({'Input (Quantity)': X[:5, 0], 'Label (is_international)': y[:5]})
labels_known

,Input (Quantity),Label (is_international)
0,3.0,0.0
1,8.0,0.0
2,4.0,0.0
3,3.0,0.0
4,10.0,0.0


**Interpret:** Every row has a known correct label. Supervised learning uses exactly this: input + true answer, together, during training.


## 7. Unsupervised Deep Learning

**Explain:** The network trains on **unlabeled data** and finds structure by itself (e.g. compressing and reconstructing the input — an autoencoder).

**Analogy:** Sorting a pile of photos into groups without anyone telling you the categories.

**Implement:**

In [10]:
autoencoder = nn.Sequential(nn.Linear(2, 1), nn.Linear(1, 2))   # compress 2 -> 1 -> reconstruct
x_sample = torch.tensor(X[:5])
reconstructed = autoencoder(x_sample)
print("Original:\n", x_sample.detach().numpy().round(1))
print("Reconstructed (untrained):\n", reconstructed.detach().numpy().round(1))

Original:
 [[ 3.   2.1]
 [ 8.   5. ]
 [ 4.   4.2]
 [ 3.   0.8]
 [10.   0.8]]
Reconstructed (untrained):
 [[-0.7  1.2]
 [-0.8  2.6]
 [-0.7  1.8]
 [-0.7  0.9]
 [-0.8  2. ]]


**Interpret:** No labels (`y`) were used anywhere — only the inputs themselves. The autoencoder's job is to compress and rebuild the input, which is a classic unsupervised task.


## 8. Neural Network Terminology

### 8.1 Neuron
**Explain:** A neuron = weighted sum of inputs + bias, passed through an activation.
**Analogy:** A judge scoring a performance using weighted criteria plus their personal bias.
**Implement:**

In [11]:
def neuron(x, w, b):
    return 1 / (1 + np.exp(-(np.dot(x, w) + b)))     # sigmoid activation

output = neuron(x=[2.0, 1.0], w=[0.5, -0.5], b=0.1)
print("Neuron output:", round(output, 3))

Neuron output: 0.646


**Interpret:** One number in, weights + bias applied, one number out — the basic unit of every neural network.

### 8.2 Input
**Explain:** The raw data fed into the network.
**Analogy:** Ingredients handed to a chef.
**Implement:**

In [12]:
print("Input vector:", X[0])

Input vector: [3.   2.08]


**Interpret:** This is exactly what the network sees — nothing more, nothing less.

### 8.3 Weight
**Explain:** A learnable number scaling one input's importance.
**Analogy:** How much a factor counts in a decision.
**Implement:**

In [13]:
for w0 in [-1, 0, 1]:
    print(f"weight={w0}: output={neuron([2.0, 1.0], [w0, -0.5], 0.1):.3f}")

weight=-1: output=0.083
weight=0: output=0.401
weight=1: output=0.832


**Interpret:** Changing one weight changes how much that input pushes the output up or down.

### 8.4 Bias
**Explain:** A learnable shift, independent of the inputs.
**Analogy:** A judge's personal baseline leniency.
**Implement:**

In [14]:
for b in [-2, 0, 2]:
    print(f"bias={b}: output={neuron([2.0, 1.0], [0.5, -0.5], b):.3f}")

bias=-2: output=0.182
bias=0: output=0.622
bias=2: output=0.924


**Interpret:** The bias shifts the output up/down uniformly, no matter what the inputs are.

### 8.5 Activation
**Explain:** A non-linear function applied after the weighted sum — this is what lets networks learn curved patterns.
**Analogy:** A thermostat switch: it reacts in a specific non-linear way, not smoothly.
**Implement:**

In [15]:
z = torch.tensor([-2.0, 0.0, 2.0])
print("Sigmoid:", torch.sigmoid(z).tolist())
print("ReLU:   ", torch.relu(z).tolist())

Sigmoid: [0.11920291930437088, 0.5, 0.8807970285415649]
ReLU:    [0.0, 0.0, 2.0]


**Interpret:** Sigmoid squashes values into (0,1). ReLU zeroes out negatives and keeps positives unchanged. Both add non-linearity.

### 8.6 Layer
**Explain:** A group of neurons processing the same input in parallel.
**Analogy:** A row of judges scoring the same performance independently.
**Implement:**

In [17]:
layer = nn.Linear(in_features=2, out_features=3)  
print(layer(torch.tensor(X[0])).detach().numpy().round(3))

[ 1.922  1.114 -3.002]


**Interpret:** 3 different outputs from the same input — each neuron has its own weights/bias.

### 8.7 Input Layer
**Explain:** Just the raw features, one slot per feature — not really "computed".
**Analogy:** The intake form before any diagnosis happens.
**Implement:**

In [18]:
print("Input layer size:", X.shape[1])

Input layer size: 2


**Interpret:** Fixed by the data — we have 2 features, so 2 input slots.

### 8.8 Hidden Layer
**Explain:** Sits between input and output; an internal, learned representation we don't directly interpret.
**Analogy:** A doctor's internal reasoning between symptoms and diagnosis.
**Implement:**

In [19]:
hidden = nn.Sequential(nn.Linear(2, 4), nn.ReLU())
print(hidden(torch.tensor(X[0])).detach().numpy().round(3))

[0.454 0.    0.251 0.487]


**Interpret:** These 4 numbers aren't directly meaningful to us, but the next layer uses them to make its decision.

### 8.9 Output Layer
**Explain:** Produces the final answer, in the format the task needs.
**Analogy:** The doctor's final diagnosis slip.
**Implement:**

In [20]:
model = nn.Sequential(nn.Linear(2, 4), nn.ReLU(), nn.Linear(4, 1), nn.Sigmoid())
print("Predicted probability:", round(model(torch.tensor(X[0])).item(), 3))

Predicted probability: 0.399


**Interpret:** One final number between 0 and 1 — exactly what we need for a yes/no prediction.

### 8.10 Parameters
**Explain:** The weights and biases the network **learns**.
**Analogy:** All the dials on a mixing console, tuned during training.
**Implement:**

In [21]:
n_params = sum(p.numel() for p in model.parameters())
print("Total learnable parameters:", n_params)

Total learnable parameters: 17


**Interpret:** Even this tiny model has several parameters to learn — real networks can have millions.

### 8.11 Hyperparameters
**Explain:** Settings **we** choose before training (not learned).
**Analogy:** Oven temperature and baking time — set by the baker, not learned by the cake.
**Implement:**

In [22]:
for hidden_size in [2, 8]:
    m = nn.Sequential(nn.Linear(2, hidden_size), nn.Linear(hidden_size, 1))
    print(f"hidden_size={hidden_size} -> {sum(p.numel() for p in m.parameters())} parameters")

hidden_size=2 -> 9 parameters
hidden_size=8 -> 33 parameters


**Interpret:** We picked `hidden_size` ourselves — it directly controls how many parameters the model must learn.

### 8.12 Tensor
**Explain:** The core data structure in PyTorch — a multi-dimensional array of numbers.
**Analogy:** A container that can hold numbers as a single value, a list, a table, or a stack of tables.
**Implement:**

In [23]:
for t in [torch.tensor(5.0), torch.tensor([1.0, 2.0]), torch.tensor(X[:2])]:
    print("shape:", tuple(t.shape))

shape: ()
shape: (2,)
shape: (2, 2)


**Interpret:** A single number, a list, and a small table are all just tensors of different shapes.

### 8.13 Model
**Explain:** Architecture + learned parameters, together.
**Analogy:** A trained chef = their techniques (architecture) + everything they've practiced (parameters).
**Implement:**

In [24]:
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
  (3): Sigmoid()
)


**Interpret:** This is a complete model — an architecture ready to be trained (or, once trained, ready to make real predictions). Notebook 2 covers how training actually adjusts its parameters.